### ISSUE TITLE
i have window.. when i run .. i get this error.. how to fix

### ISSUE THREAD

**Issue by guardianx9** [nzblnk/nzb-monkey#13]
NZB-Monkey v0.2.1
 =================
Traceback (most recent call last):
  File "nzbmonkey.py", line 1733, in <module>
  File "nzbmonkey.py", line 1332, in main
  File "C:\dev\Tools\python34\lib\site-packages\configobj.py", line 1229, in __i
nit__
  File "C:\dev\Tools\python34\lib\site-packages\configobj.py", line 1318, in _lo
ad
configobj.DuplicateError: Duplicate keyword name at line 12.

C:\Users\hope\Downloads\nzbmonkey-v0.2.1-win>

**Comment by nzblnk** [comment]
This is literally what it says: a key in you config file appears (accidentally) double. Please remove one of them doubles.
