### ISSUE TITLE
Pushing to Synology (with DSM7.x) failing - latest NZBMONKEY version (0.27)

### ISSUE THREAD

**Issue by MrScripter85** [nzblnk/nzb-monkey#39]
- Pushing to SYNOLOGY-DLS ...Traceback (most recent call last):
  File "C:\dev\python\nzb-monkey-github\src\nzbmonkey.py", line 1751, in <module>
  File "C:\dev\python\nzb-monkey-github\src\nzbmonkey.py", line 1671, in main
  File "C:\dev\python\nzb-monkey-github\src\nzbmonkey.py", line 1308, in push_nzb_synologydls
TypeError: can only concatenate str (not "NoneType") to str

any idea whats wrong?

**Comment by MrScripter85** [comment]
The NZB doesnt have a password. Other NZBs with a password work.
